ALTER TABLE `codRemittances` MODIFY COLUMN `status` enum('draft','pending','processed','completed') NOT NULL DEFAULT 'pending';
--> statement-breakpoint
ALTER TABLE `codRemittances` ADD `kind` varchar(10);
--> statement-breakpoint
ALTER TABLE `codRemittances` ADD `periodCutoff` timestamp NULL;
--> statement-breakpoint
ALTER TABLE `codRemittances` ADD `offsetAmount` varchar(50) DEFAULT '0' NOT NULL;
--> statement-breakpoint
ALTER TABLE `codRemittances` ADD `autoGenerated` int DEFAULT 0 NOT NULL;
--> statement-breakpoint
CREATE TABLE `codRemittanceOffsets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`remittanceId` int NOT NULL,
	`invoiceId` int NOT NULL,
	`amount` varchar(50) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `codRemittanceOffsets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE INDEX `codRemittanceOffsets_remittanceId_idx` ON `codRemittanceOffsets` (`remittanceId`);
--> statement-breakpoint
CREATE INDEX `codRemittanceOffsets_invoiceId_idx` ON `codRemittanceOffsets` (`invoiceId`);
--> statement-breakpoint
ALTER TABLE `clientAccounts` ADD `codOffsetInvoices` int DEFAULT 0 NOT NULL;
