ALTER TABLE clientAccounts
  ADD COLUMN zone1BaseRate VARCHAR(20) NULL,
  ADD COLUMN zone1PerKg    VARCHAR(20) NULL,
  ADD COLUMN zone2BaseRate VARCHAR(20) NULL,
  ADD COLUMN zone2PerKg    VARCHAR(20) NULL,
  ADD COLUMN zone3BaseRate VARCHAR(20) NULL,
  ADD COLUMN zone3PerKg    VARCHAR(20) NULL;
