/**
 * Weekly billing automation (migration 0043) — schema + production config.
 *
 *  Schema (idempotent):
 *   - codRemittances.status gains 'draft'; new kind / periodCutoff / offsetAmount / autoGenerated
 *   - codRemittanceOffsets table (client invoices netted against a remittance)
 *   - clientAccounts.codOffsetInvoices
 *
 *  Config (only inserted when missing, never overwrites a value staff changed):
 *   - ADDRESS_ISSUE_FEE = 5, ADDRESS_ISSUE_FEE_FROM = 2026-10-06
 *   - CARD_COD_REMIT_ANCHOR = 2026-10-16 (first bi-weekly card cutoff, Friday)
 *   - BILLING_AUTOMATION_EXCLUDED_CLIENTS = 12,28 (internal test accounts)
 *
 *  Client data (production only, --skip-clients to leave it alone):
 *   - weekly: Noor and grace, Bare Essentials, Kuolalyte, Prasha, Steal The Show, House of Wani
 *   - monthly: BAGONISTA
 *   - Prasha nets its invoices against COD payouts (codOffsetInvoices = 1)
 *
 * Usage:
 *   npx tsx scripts/add-billing-automation.ts --dry-run
 *   npx tsx scripts/add-billing-automation.ts
 *   npx tsx scripts/add-billing-automation.ts --test     (TEST_DATABASE_URL, schema only)
 */

import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import path from 'path';
import { URL } from 'url';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const DRY_RUN = process.argv.includes('--dry-run');
const TEST_TARGET = process.argv.includes('--test');
const SKIP_CLIENTS = TEST_TARGET || process.argv.includes('--skip-clients');

const rawUrl = TEST_TARGET ? process.env.TEST_DATABASE_URL : process.env.DATABASE_URL;
if (!rawUrl) {
    console.error(`❌ ${TEST_TARGET ? 'TEST_DATABASE_URL' : 'DATABASE_URL'} not set`);
    process.exit(1);
}
const parsedUrl = new URL(rawUrl);
const database = parsedUrl.pathname.slice(1);

const CONFIG_DEFAULTS: Array<[string, string, string]> = [
    ['ADDRESS_ISSUE_FEE', '5', 'AED charged once per shipment that was ever marked address_issue'],
    ['ADDRESS_ISSUE_FEE_FROM', '2026-10-06', 'Only address_issue events on/after this date are charged'],
    ['CARD_COD_REMIT_ANCHOR', '2026-10-16', 'A Friday: card COD is remitted bi-weekly on cutoffs 14 days apart from this date'],
    ['BILLING_AUTOMATION_EXCLUDED_CLIENTS', '12,28', 'Client ids the weekly automation never drafts invoices/remittances for'],
];

// [id, expected companyName prefix, settlement period, codOffsetInvoices]
const CLIENT_SETTINGS: Array<[number, string, 'weekly' | 'monthly', number]> = [
    [13, 'Noor and grace', 'weekly', 0],
    [18, 'Bare Essentials', 'weekly', 0],
    [25, 'Kuolalyte', 'weekly', 0],
    [26, 'Prasha', 'weekly', 1],
    [27, 'Steal The Show', 'weekly', 0],
    [63, 'House of Wani', 'weekly', 0],
    [19, 'BAGONISTA', 'monthly', 0],
];

async function main() {
    console.log(`🔌 ${TEST_TARGET ? 'TEST' : 'PRODUCTION'} database "${database}"${DRY_RUN ? ' (dry run)' : ''}`);
    const connection = await mysql.createConnection({
        host: parsedUrl.hostname,
        port: Number(parsedUrl.port) || 3306,
        user: parsedUrl.username,
        password: parsedUrl.password,
        database,
        ssl: { rejectUnauthorized: false },
    });

    const run = async (label: string, sql: string, params: unknown[] = []) => {
        if (DRY_RUN) { console.log(`  [dry-run] ${label}`); return; }
        await connection.query(sql, params);
        console.log(`  ✅ ${label}`);
    };
    const columnExists = async (table: string, column: string) => {
        const [rows] = await connection.query<mysql.RowDataPacket[]>(
            'SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ? LIMIT 1',
            [database, table, column],
        );
        return rows.length > 0;
    };
    const tableExists = async (table: string) => {
        const [rows] = await connection.query<mysql.RowDataPacket[]>(
            'SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? LIMIT 1',
            [database, table],
        );
        return rows.length > 0;
    };

    try {
        // ── Schema ──────────────────────────────────────────────────────────
        const [statusCol] = await connection.query<mysql.RowDataPacket[]>(
            "SELECT COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = 'codRemittances' AND COLUMN_NAME = 'status'",
            [database],
        );
        if (!String(statusCol[0]?.COLUMN_TYPE ?? '').includes("'draft'")) {
            await run("codRemittances.status += 'draft'",
                "ALTER TABLE `codRemittances` MODIFY COLUMN `status` enum('draft','pending','processed','completed') NOT NULL DEFAULT 'pending'");
        } else console.log("  ⚠️ codRemittances.status already has 'draft'");

        const remittanceColumns: Array<[string, string]> = [
            ['kind', 'ALTER TABLE `codRemittances` ADD `kind` varchar(10)'],
            ['periodCutoff', 'ALTER TABLE `codRemittances` ADD `periodCutoff` timestamp NULL'],
            ['offsetAmount', "ALTER TABLE `codRemittances` ADD `offsetAmount` varchar(50) NOT NULL DEFAULT '0'"],
            ['autoGenerated', 'ALTER TABLE `codRemittances` ADD `autoGenerated` int NOT NULL DEFAULT 0'],
        ];
        for (const [column, sql] of remittanceColumns) {
            if (!(await columnExists('codRemittances', column))) await run(`codRemittances.${column} added`, sql);
            else console.log(`  ⚠️ codRemittances.${column} already exists`);
        }

        if (!(await tableExists('codRemittanceOffsets'))) {
            await run('codRemittanceOffsets created', `CREATE TABLE \`codRemittanceOffsets\` (
                \`id\` int AUTO_INCREMENT NOT NULL,
                \`remittanceId\` int NOT NULL,
                \`invoiceId\` int NOT NULL,
                \`amount\` varchar(50) NOT NULL,
                \`createdAt\` timestamp NOT NULL DEFAULT (now()),
                CONSTRAINT \`codRemittanceOffsets_id\` PRIMARY KEY(\`id\`),
                INDEX \`codRemittanceOffsets_remittanceId_idx\` (\`remittanceId\`),
                INDEX \`codRemittanceOffsets_invoiceId_idx\` (\`invoiceId\`)
            )`);
        } else console.log('  ⚠️ codRemittanceOffsets already exists');

        if (!(await columnExists('clientAccounts', 'codOffsetInvoices'))) {
            await run('clientAccounts.codOffsetInvoices added', 'ALTER TABLE `clientAccounts` ADD `codOffsetInvoices` int NOT NULL DEFAULT 0');
        } else console.log('  ⚠️ clientAccounts.codOffsetInvoices already exists');

        // ── Config ──────────────────────────────────────────────────────────
        if (!TEST_TARGET) {
            for (const [key, value, description] of CONFIG_DEFAULTS) {
                const [existing] = await connection.query<mysql.RowDataPacket[]>(
                    'SELECT configValue FROM serviceConfig WHERE configKey = ? LIMIT 1', [key]);
                if (existing.length) {
                    console.log(`  ⚠️ ${key} already set (${existing[0].configValue}), leaving it`);
                    continue;
                }
                await run(`${key} = ${value}`,
                    'INSERT INTO serviceConfig (configKey, configValue, description) VALUES (?, ?, ?)', [key, value, description]);
            }
        }

        // ── Clients ─────────────────────────────────────────────────────────
        if (!SKIP_CLIENTS) {
            // In a dry run the column may not exist yet — read it as 0.
            const offsetColumn = (await columnExists('clientAccounts', 'codOffsetInvoices')) ? 'codOffsetInvoices' : '0 AS codOffsetInvoices';
            for (const [id, namePrefix, period, offset] of CLIENT_SETTINGS) {
                const [rows] = await connection.query<mysql.RowDataPacket[]>(
                    `SELECT companyName, defaultSettlementPeriod, ${offsetColumn} FROM clientAccounts WHERE id = ?`, [id]);
                const client = rows[0];
                if (!client || !String(client.companyName).startsWith(namePrefix)) {
                    console.log(`  ❌ client ${id} is not "${namePrefix}…" (${client?.companyName ?? 'missing'}) — skipped`);
                    continue;
                }
                if (client.defaultSettlementPeriod === period && Number(client.codOffsetInvoices ?? 0) === offset) {
                    console.log(`  ⚠️ ${client.companyName}: already ${period}${offset ? ' + invoice offset' : ''}`);
                    continue;
                }
                await run(`${client.companyName}: ${client.defaultSettlementPeriod} → ${period}${offset ? ', nets invoices against COD' : ''}`,
                    'UPDATE clientAccounts SET defaultSettlementPeriod = ?, codOffsetInvoices = ? WHERE id = ?', [period, offset, id]);
            }
        }

        console.log(DRY_RUN ? '\nℹ️  Dry run only — re-run without --dry-run to apply.' : '\n✅ Done');
    } catch (error) {
        console.error('❌ Migration failed:', error);
        process.exitCode = 1;
    } finally {
        await connection.end();
    }
}

main();
